name: Rest Assured Java Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ubuntu-chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Set up Chrome WebDriver
        run: |
          sudo apt-get install -y chromium-chromedriver
          if [ ! -f /usr/bin/chromedriver ]; then
            sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          fi

      - name: Build and Test with Maven - Chrome
        run: mvn clean test -Dbrowser=chrome

      - name: Upload Test Results - Chrome
        uses: actions/upload-artifact@v2
        with:
          name: test-results-chrome
          path: target/surefire-reports  # Adjust path based on your Maven configuration

  test-ubuntu-firefox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Set up Firefox WebDriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
          tar -xzf geckodriver-v0.30.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Build and Test with Maven - Firefox
        run: mvn clean test -Dbrowser=firefox

      - name: Upload Test Results - Firefox
        uses: actions/upload-artifact@v2
        with:
          name: test-results-firefox
          path: target/surefire-reports  # Adjust path based on your Maven configuration

  test-ubuntu-edge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Set up Edge WebDriver (Placeholder for Ubuntu)
        run: echo "No Edge WebDriver setup needed for Ubuntu"

      - name: Build and Test with Maven - Edge
        run: mvn clean test -Dbrowser=edge

      - name: Upload Test Results - Edge
        uses: actions/upload-artifact@v2
        with:
          name: test-results-edge
          path: target/surefire-reports  # Adjust path based on your Maven configuration

  test-macos-chrome:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: brew install maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Set up Chrome WebDriver
        run: |
          brew install chromedriver

      - name: Build and Test with Maven - Chrome
        run: mvn clean test -Dbrowser=chrome

      - name: Upload Test Results - Chrome
        uses: actions/upload-artifact@v2
        with:
          name: test-results-chrome
          path: target/surefire-reports  # Adjust path based on your Maven configuration

  test-macos-firefox:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: brew install maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Set up Firefox WebDriver
        run: |
          brew install geckodriver

      - name: Build and Test with Maven - Firefox
        run: mvn clean test -Dbrowser=firefox

      - name: Upload Test Results - Firefox
        uses: actions/upload-artifact@v2
        with:
          name: test-results-firefox
          path: target/surefire-reports  # Adjust path based on your Maven configuration

  test-macos-edge:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: brew install maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Set up Edge WebDriver (Placeholder for macOS)
        run: echo "No Edge WebDriver setup needed for macOS"

      - name: Build and Test with Maven - Edge
        run: mvn clean test -Dbrowser=edge

      - name: Upload Test Results - Edge
        uses: actions/upload-artifact@v2
        with:
          name: test-results-edge
          path: target/surefire-reports  # Adjust path based on your Maven configuration

  test-windows-chrome:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: |
          choco install -y maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Set up Chrome WebDriver
        run: |
          choco install -y chromedriver

      - name: Build and Test with Maven - Chrome
        run: mvn clean test -Dbrowser=chrome

      - name: Upload Test Results - Chrome
        uses: actions/upload-artifact@v2
        with:
          name: test-results-chrome
          path: target/surefire-reports  # Adjust path based on your Maven configuration

  test-windows-firefox:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: |
          choco install -y maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Set up Firefox WebDriver
        run: |
          choco install -y geckodriver

      - name: Build and Test with Maven - Firefox
        run: mvn clean test -Dbrowser=firefox

      - name: Upload Test Results - Firefox
        uses: actions/upload-artifact@v2
        with:
          name: test-results-firefox
          path: target/surefire-reports  # Adjust path based on your Maven configuration

  test-windows-edge:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: |
          choco install -y maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Set up Edge WebDriver
        run: |
          echo "Placeholder for installing Edge WebDriver on Windows"

      - name: Build and Test with Maven - Edge
        run: mvn clean test -Dbrowser=edge

      - name: Upload Test Results - Edge
        uses: actions/upload-artifact@v2
        with:
          name: test-results-edge
          path: target/surefire-reports  # Adjust path based on your Maven configuration
